### ISSUE TITLE
Issue Running

### ISSUE THREAD

**Issue by ChrisiCarr** [anthonyheddings/autotorrent#1]
I wanted to give this a go but got the error below, any idea what it is?

C:\Users\k\Desktop\autotorrent-master>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from tpb import TPB
  File "C:\Users\k\Desktop\autotorrent-master\tpb.py", line 13, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'

**Comment by anthonyheddings** [comment]
looks like you're missing some modules, but anyway this project is horribly outdated. There's a node API for the bay, so I'm gonna whip up something with that today. I'll keep you posted.

**Comment by ChrisiCarr** [comment]
Awesome, thank you.
